### ISSUE TITLE
Notifications do not work sometimes

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/element-android#2]
### Steps to reproduce

It is not working like once rarely, but rather more 9 / 10 of the time it works fine and then 1 / 10 of the time it does not work in a row.

Maybe related to the phone setup (like battery optimization etc, have `Unrestricted` `App battery usage`, no other settings seem to interfere). Concerning in-app Element settings, the bot conversation is *notifying me for* `All messages`, I enabled `Settings` > `Notifications` > `Other` > `Messages by bot` but I do not see how it could helps, as except the username, nothing can let know that it is a bot (except possibly some kind of user agent or API use), `Delay between each Sync` is set to `60 seconds`, *starting on boot*. Otherwise I checked all other settings. Let us first verify having this issue (like should have received notifications on phone, hence check on a computer and confirm that have not received a notification on the phone application).

Note that checking manually the phone application solves the issue but is an unwanted manual behavior.

+32

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Maybe related to <code>adb logcat</code>:</summary>

```
01-12 00:52:38.239 22109 23651 W WebSocketConnection: [unidentified:21063733] onFailure()
01-12 00:52:38.239 22109 23651 W WebSocketConnection: java.io.EOFException
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:66)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 	at java.lang.Thread.run(Thread.java:1012)
01-12 00:52:38.239 22109 23651 W WebSocketConnection: 
01-12 00:52:39.588  1679  2299 I ActivityManager: Background started FGS: Allowed [callingPackage: im.vector.app; callingUid: 10147; uidState: FGS ; intent: Intent { cmp=im.vector.app/.core.services.VectorSyncAndroidService (has extras) }; code:PROC_STATE_FGS; tempAllowListReason:<,reasonCode:SYSTEM_ALLOW_LISTED,duration:9223372036854775807,callingUid:-1>; targetSdkVersion:33; callerTargetSdkVersion:33; startForegroundCount:0; bindFromPackage:null]
01-12 00:52:39.615  1679 13366 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service im.vector.app/.core.services.VectorSyncAndroidService
```
</details>

Currently:

![image](https://github.com/Benjamin-Loison/element-android/assets/12752145/6663b2bd-07e5-4afe-a588-b4b0a5e21ba8)

Let me restart the phone.

<details>
<summary>Concerning first lines possibly not related as got:</summary>

```
01-12 01:08:42.257     0     0 W healthd : battery l=45 v=4141 t=30.0 h=2 st=2 c=1746522 fc=3069000 cc=87 chg=a
01-12 01:08:45.702  1669  2285 D ConnectivityService: NetReassign [no changes]
01-12 01:08:49.507  3867  5140 W WebSocketConnection: [unidentified:163741733] onFailure()
01-12 01:08:49.507  3867  5140 W WebSocketConnection: java.io.EOFException
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:66)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 	at java.lang.Thread.run(Thread.java:1012)
01-12 01:08:49.507  3867  5140 W WebSocketConnection: 
01-12 01:08:50.370     0     0 E QCOM-STEPCHG: handle_jeita: handle_jeita ,temp:300, fcc_ua:4296000
01-12 01:08:50.370     0     0 E QCOM-STEPCHG: handle_jeita: handle_jeita ,FCC vote chg_disable_votable:false
01-12 01:08:50.370     0     0 E QCOM-STEPCHG: handle_vbatt_limit: vbatt-4143432 lower or rc-0, restored
01-12 01:08:50.386     0     0 W healthd : battery l=45 v=4143 t=30.0 h=2 st=2 c=1747742 fc=3069000 cc=87 chg=a
01-12 01:08:50.411  1669  1669 I LineageHealth: Current mChargingStopReason: 0
01-12 01:08:50.411  2642  2642 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 1
01-12 01:08:50.427  2376  3514 D PowerUI : can't show warning due to - plugged: true status unknown: false
01-12 01:08:58.352     0     0 W healthd : battery l=45 v=4142 t=30.0 h=2 st=2 c=1754456 fc=3069000 cc=87 chg=a
```
</details>

Should get logcat wireless and see what happens when face the issue.

**Comment by Benjamin-Loison** [comment]
Have again notifications it seems on 1.6.10.

**Comment by Benjamin-Loison** [comment]
I just enabled back `Notifications` > `Other` > `Listening for events`. Why do we have such a notification contrarily to Signal for instance? Related to #11.

**Comment by Benjamin-Loison** [comment]
<details>
<summary>Maybe same issue on Xiaomi Mi A3 for relative:</summary>

```
-----BEGIN PGP MESSAGE-----

hF4DTQa9Wom5MBgSAQdAlz1ORxexpv6ef7pdcXq4FzcXT/n2boT1lEabF0324SYw
ZGoUlWtMufRy/68e3txzjhKImtLJ16LrLocqVHUlEqq8E+clImQw6FjtObbC9dZa
0kAB1GxAde6SLv3AO+0UWZmuP6+CicT2qzpaEW1PieMBxxGpRV5vOwNcuQC+Z9o4
tpnmIZFLb+/OPh2VPf+TmiN0
=VRyV
-----END PGP MESSAGE-----
```
</details>

However, this phone is maybe not up-to-date notably due to #12.

Maybe related to [Benjamin-Loison/android/issues/25](https://github.com/Benjamin-Loison/android/issues/25).

**Comment by Benjamin-Loison** [comment]
Maybe we are not notified that someone share us his location, so the person sharing his location has to send a text message to make sure that the receiver is notified.

<details>
<summary>The person that told me so is:</summary>

```
-----BEGIN PGP MESSAGE-----

hF4DTQa9Wom5MBgSAQdA3QTctFRkcilh9OuYAkpqQIRFqWk2c3kMRgcmJ0BS9Csw
pLPf66xox0aeHvAQJkwtubhakVRhY4v/Yb5/oZFmcdJKyUjEXfqiUmxMHm+SgFat
0kABRtGM0U/emlXyO/M24HzQ1os6PtZMLNykdpei9o1RpBOfspzQKplswx3QpN5n
s+6YWaGCOTyxOqLb2KdSbJDJ
=NeB0
-----END PGP MESSAGE-----
```
</details>

**Comment by Benjamin-Loison** [comment]
Related to #21.

**Comment by Benjamin-Loison** [comment]
![image](https://github.com/user-attachments/assets/0de634e7-b717-43af-89cb-891c4d5fcc10)

Note: *Background synchronization* > *Background Sync Mode* > *Background synchronization* and *Delay between each Sync* and *Sync request timeout*.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/01b37c1c-ad30-4a5b-84b8-b0c0b59a39f1" />

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/684e75ad-85e5-455c-854e-642ae249a67c" />

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/17e509ab-70aa-41bb-a2c9-b6885763888c" />

On both my Fairphone 4 and Xiaomi Mi A3 LineageOS 22.2 it was set to, by default I guess, *Optimized for battery*, I switched them to *Optimized for real time*. On Samsung Galaxy A53 it is set to *Optimized for real time*, but I don't remember if it was initially *Optimized for battery*.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/24fd5e28-d22b-43b5-a3e0-2a67958960ef" />

![image](https://github.com/user-attachments/assets/17ad3fcd-aa82-4d6b-a338-173a7ccd35b1)

![image](https://github.com/user-attachments/assets/ced5d592-5e35-4e71-b573-937aaa4cc9e8)

![image](https://github.com/user-attachments/assets/ce334a88-ef04-4e5d-b2a3-4e1b8f9439b5)

![image](https://github.com/user-attachments/assets/18ae7ccd-1e88-4bee-af3f-2f5a03c9e6c9)

Have to run tests again to detect the setting change.

![image](https://github.com/user-attachments/assets/e8a47b26-f6bf-4666-acea-2efdb82ffbc5)

Still same sections on my Fairphone 4 LineageOS 22.2.

**Comment by Benjamin-Loison** [comment]
Related to [Benjamin_Loison/tchap-android/issues/2](https://codeberg.org/Benjamin_Loison/tchap-android/issues/2).
